### ISSUE TITLE
First Draft of Project 4

### ISSUE THREAD

**Issue by indefinitelee** [indefinitelee/FPL-Stats#1]
Be ruthless. If this idea sucks, let's kill it now. 

Is this of appropriate size/scope for a final project?
Is the intent clear? If not, what requires further explanation?
Do you foresee any problems/difficulties that I have not mentioned?

Thanks

@gittheking
@jasonseminara
@trevorpreston
@rapala61
@irwintsay

**Comment by gittheking** [comment]
@indefinitelee I think this is a really cool idea. I would highly suggest you come up with a more concrete plan of what you consider your MVP. As for the database choice, it's really up to you. I don't see why you couldn't have this relational, but if it makes more sense for you to do it with Mongo that would be fine too - the right tool is the one you feel more comfortable with.

**Comment by gittheking** [comment]
@indefinitelee btw - if it wasn't clear, this is approved.
