### ISSUE TITLE
getting a backend error due to no props but fetch to get props is not runnig

### ISSUE THREAD

**Issue by indefinitelee** [indefinitelee/FPL-Stats#5]
First, 

My App has componentDidMount which calls the function .getStats that runs the fetch on the backend (this is to work around CORS issue). 
my fetch returns the needed object if i hit the route directly. 
The fetch data should be passed into state and then sent as props to Table. 

However, I am getting Table.jsx:10 Uncaught TypeError: Cannot read property 'props' of undefined(…)

It is hitting Table.jsx and  before the componentDidMount (console.logs in App.jsx don't print)
I;ve tried changing various component/mount things and even removing componentMount entirely. 
Not sure what else to try. 

In addition, nothing is rendering on page - I had login/signup rendering all day yesterday and this morning. All that changed was I restarted computer ( a mistake which will not be repeated). 

@rapala61
@gittheking
@irwintsay
@jasonseminara
@trevorpreston
pls holla back with an acknowledgement or ETA. 
grazie tutti.

**Comment by indefinitelee** [comment]
needed an additional       .then(r => r.json()) on front end, 
was setting state in incorrect place on backend, only react can touch state
was referencing data incorrectly in route, duh. 

thanks Iriwn.

**Comment by jasonseminara** [comment]
@indefinitelee is this closed?
